"""Update schema: soft deletes, cart, logistics enum, and role

Revision ID: 357976713a4f
Revises: a94a69662524
Create Date: 2026-08-20 09:33:52.284635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '357976713a4f'
down_revision = 'a94a69662524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cart_items',
    sa.Column('cart_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='cart_items_quantity_check'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id', 'product_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=False))
        # DELETE ALTER COLUMN FOR STATUS

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        # DELETE ALTER COLUMN FOR ROLE

    # ==========================================================
    # INJEKSI RAW SQL UNTUK ENUM MIGRATION (UPGRADE)
    # ==========================================================
    
    # 1. USERS.ROLE
    op.execute("ALTER TYPE user_role RENAME TO old_user_role")
    op.execute("CREATE TYPE system_role AS ENUM('admin', 'user')")
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE system_role USING role::text::system_role")
    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'user'")
    op.execute("DROP TYPE old_user_role")

    # 2. ORDERS.STATUS
    op.execute("ALTER TYPE order_status RENAME TO old_order_status")
    op.execute("CREATE TYPE order_logistics_status AS ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled')")
    op.execute("ALTER TABLE orders ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE orders ALTER COLUMN status TYPE order_logistics_status USING status::text::order_logistics_status")
    op.execute("ALTER TABLE orders ALTER COLUMN status SET DEFAULT 'pending'")
    op.execute("DROP TYPE old_order_status")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('shipping_address')

    op.drop_table('cart_items')
    op.drop_table('carts')
    
    # ==========================================================
    # INJEKSI RAW SQL UNTUK ENUM MIGRATION (DOWNGRADE)
    # ==========================================================
    
    # 1. USERS.ROLE
    op.execute("ALTER TYPE system_role RENAME TO old_system_role")
    op.execute("CREATE TYPE user_role AS ENUM('admin', 'buyer', 'seller')")
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE user_role USING role::text::user_role")
    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'buyer'")
    op.execute("DROP TYPE old_system_role")

    # 2. ORDERS.STATUS
    op.execute("ALTER TYPE order_logistics_status RENAME TO old_order_logistics_status")
    op.execute("CREATE TYPE order_status AS ENUM('PENDING', 'PAID', 'SHIPPED', 'CANCELED')")
    op.execute("ALTER TABLE orders ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE orders ALTER COLUMN status TYPE order_status USING status::text::order_status")
    op.execute("ALTER TABLE orders ALTER COLUMN status SET DEFAULT 'PENDING'")
    op.execute("DROP TYPE old_order_logistics_status")