"""add user role enum, implement sellers table architecture, also the logic that contains roles and seller

Revision ID: 5589b26e9258
Revises: 9ac5330e8f72
Create Date: 2026-08-13 18:44:38.970665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5589b26e9258'
down_revision = '9ac5330e8f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('admin', 'buyer', 'seller', name='user_role').create(op.get_bind())
    op.create_table('sellers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('store_description', sa.String(length=999), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_name')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'sellers', ['seller_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('admin', 'buyer', 'seller', name='user_role'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('seller_id')

    op.drop_table('sellers')
    sa.Enum('admin', 'buyer', 'seller', name='user_role').drop(op.get_bind())
    # ### end Alembic commands ###
