"""Fixing and Improving Models

Revision ID: a94a69662524
Revises: 5589b26e9258
Create Date: 2026-08-14 11:26:50.374004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94a69662524'
down_revision = '5589b26e9258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=999),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=999),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('store_description',
               existing_type=sa.VARCHAR(length=999),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.alter_column('store_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=999),
               existing_nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=999),
               existing_nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=999),
               existing_nullable=True)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
